### ISSUE TITLE
Deleting application leaves mail/post traffic behind

### ISSUE THREAD

**Issue by schuergi** [techorix/semtix#1]
due to the nature of the project (it's for german universities), i'll leave my report here in german...
beim löschen eines antrages bleiben die Textblöcke erhalten, wenn eine neuer antrag für dieselbe angelegt wird, tauchen die nachfragetexte wieder auf.
erwartbar wäre ein löschen auch der entsprechenden nachfrageliste.

**Comment by schuergi** [comment]
restarting db program fixes this

**Comment by techorix** [comment]
Viele solcher Probleme (vielleicht aber nicht dieses spezielle) hängen mit der Implementierung des GUI zusammen. Oft wird die graphische Komponente einfach im Speicher belassen und dann beim Neuanlegen eines Datensatzes und Öffnen der Komponenten werden einfach die alten Inhalte wiederhergestellt. Dazu müsste man das Neurendern der jeweiligen graphischen Komponente aufwendiger implementieren.
